### ISSUE TITLE
Help with using janel with a java 11 modular app using jpackage

### ISSUE THREAD

**Issue by matintokyo** [michaelknigge/janel#2]
Hi! I came accross janel as I looked for a launcher able to handle non-ascii characters in filenames when using file associations in windows with my java 11 modular app.

I can't seem to figure the correct paths for -Djava.class.path and janel.main.class; and I'm not really sure either where I should place the .exe and .lap files within the directory tree created by jpackage. 

(I am using jpackage via the beryx/badass-jlink-plugin).

Any suggestions on how to configure would be greatly appreciated!
Thank you.

For reference, below is the jpackage directory tree content.
My exe is SekiWari.exe and jar containing MainApp class is suwari.jar

Also here is the actual jpackage build: https://www.dropbox.com/s/o24tfszo3f3y82g/SekiWari.7z?dl=1

File List:
=====
SekiWari\.jpackage.xml
--
SekiWari\api-ms-win-core-console-l1-1-0.dll
SekiWari\api-ms-win-core-datetime-l1-1-0.dll
SekiWari\api-ms-win-core-debug-l1-1-0.dll
SekiWari\api-ms-win-core-errorhandling-l1-1-0.dll
SekiWari\api-ms-win-core-file-l1-1-0.dll
SekiWari\api-ms-win-core-file-l1-2-0.dll
SekiWari\api-ms-win-core-file-l2-1-0.dll
SekiWari\api-ms-win-core-handle-l1-1-0.dll
SekiWari\api-ms-win-core-heap-l1-1-0.dll
SekiWari\api-ms-win-core-interlocked-l1-1-0.dll
SekiWari\api-ms-win-core-libraryloader-l1-1-0.dll
SekiWari\api-ms-win-core-localization-l1-2-0.dll
SekiWari\api-ms-win-core-memory-l1-1-0.dll
SekiWari\api-ms-win-core-namedpipe-l1-1-0.dll
SekiWari\api-ms-win-core-processenvironment-l1-1-0.dll
SekiWari\api-ms-win-core-processthreads-l1-1-0.dll
SekiWari\api-ms-win-core-processthreads-l1-1-1.dll
SekiWari\api-ms-win-core-profile-l1-1-0.dll
SekiWari\api-ms-win-core-rtlsupport-l1-1-0.dll
SekiWari\api-ms-win-core-string-l1-1-0.dll
SekiWari\api-ms-win-core-synch-l1-1-0.dll
SekiWari\api-ms-win-core-synch-l1-2-0.dll
SekiWari\api-ms-win-core-sysinfo-l1-1-0.dll
SekiWari\api-ms-win-core-timezone-l1-1-0.dll
SekiWari\api-ms-win-core-util-l1-1-0.dll
SekiWari\api-ms-win-crt-conio-l1-1-0.dll
SekiWari\api-ms-win-crt-convert-l1-1-0.dll
SekiWari\api-ms-win-crt-environment-l1-1-0.dll
SekiWari\api-ms-win-crt-filesystem-l1-1-0.dll
SekiWari\api-ms-win-crt-heap-l1-1-0.dll
SekiWari\api-ms-win-crt-locale-l1-1-0.dll
SekiWari\api-ms-win-crt-math-l1-1-0.dll
SekiWari\api-ms-win-crt-multibyte-l1-1-0.dll
SekiWari\api-ms-win-crt-private-l1-1-0.dll
SekiWari\api-ms-win-crt-process-l1-1-0.dll
SekiWari\api-ms-win-crt-runtime-l1-1-0.dll
SekiWari\api-ms-win-crt-stdio-l1-1-0.dll
SekiWari\api-ms-win-crt-string-l1-1-0.dll
SekiWari\api-ms-win-crt-time-l1-1-0.dll
SekiWari\api-ms-win-crt-utility-l1-1-0.dll
SekiWari\app
SekiWari\applauncher.dll
SekiWari\msvcp140.dll
SekiWari\runtime
SekiWari\SekiWari-backup.exe
SekiWari\SekiWari.exe
SekiWari\SekiWari.ico
SekiWari\SekiWari.lap
SekiWari\ucrtbase.dll
SekiWari\vcruntime140.dll
SekiWari\app\mods
SekiWari\app\SekiWari.cfg
SekiWari\app\mods\bcmail-jdk14-1.38.jar
SekiWari\app\mods\bcprov-jdk14-1.38.jar
SekiWari\app\mods\bctsp-jdk14-1.38.jar
SekiWari\app\mods\castor-core-1.4.1.jar
SekiWari\app\mods\castor-xml-1.4.1.jar
SekiWari\app\mods\commons-beanutils-1.9.3.jar
SekiWari\app\mods\commons-codec-1.11.jar
SekiWari\app\mods\commons-collections-3.2.2.jar
SekiWari\app\mods\commons-collections4-4.2.jar
SekiWari\app\mods\commons-compress-1.18.jar
SekiWari\app\mods\commons-digester-2.1.jar
SekiWari\app\mods\commons-lang3-3.4.jar
SekiWari\app\mods\commons-logging-1.2.jar
SekiWari\app\mods\commons-math3-3.6.1.jar
SekiWari\app\mods\controlsfx-11.0.1.jar
SekiWari\app\mods\curvesapi-1.05.jar
SekiWari\app\mods\easybind-1.0.3.jar
SekiWari\app\mods\ecj-4.4.2.jar
SekiWari\app\mods\ikonli-core-11.3.4.jar
SekiWari\app\mods\ikonli-entypo-pack-11.3.4.jar
SekiWari\app\mods\ikonli-fontawesome-pack-11.3.4.jar
SekiWari\app\mods\ikonli-javafx-11.3.4.jar
SekiWari\app\mods\ikonli-materialdesign-pack-11.3.4.jar
SekiWari\app\mods\ikonli-openiconic-pack-11.3.4.jar
SekiWari\app\mods\itext-2.1.7.jar
SekiWari\app\mods\jackson-annotations-2.9.9.jar
SekiWari\app\mods\jackson-core-2.9.9.jar
SekiWari\app\mods\jackson-databind-2.9.9.jar
SekiWari\app\mods\jasperreports-6.10.0.jar
SekiWari\app\mods\jasperreports-fonts-6.10.0.jar
SekiWari\app\mods\javafx-base-11.0.2-win.jar
SekiWari\app\mods\javafx-controls-11.0.2-win.jar
SekiWari\app\mods\javafx-fxml-11.0.2-win.jar
SekiWari\app\mods\javafx-graphics-11.0.2-win.jar
SekiWari\app\mods\javafx-swing-11.0.2-win.jar
SekiWari\app\mods\javax.inject-1.jar
SekiWari\app\mods\jcommon-1.0.23.jar
SekiWari\app\mods\jfreechart-1.0.19.jar
SekiWari\app\mods\poi-4.0.1.jar
SekiWari\app\mods\poi-ooxml-4.0.1.jar
SekiWari\app\mods\poi-ooxml-schemas-4.0.1.jar
SekiWari\app\mods\sekiwarifonts.jar
SekiWari\app\mods\suwari.jar
SekiWari\app\mods\suwari.merged.module.jar
SekiWari\app\mods\xmlbeans-3.0.2.jar
SekiWari\runtime\bin
SekiWari\runtime\conf
SekiWari\runtime\legal
SekiWari\runtime\lib
SekiWari\runtime\release
SekiWari\runtime\bin\api-ms-win-core-console-l1-1-0.dll
SekiWari\runtime\bin\api-ms-win-core-datetime-l1-1-0.dll
SekiWari\runtime\bin\api-ms-win-core-debug-l1-1-0.dll
SekiWari\runtime\bin\api-ms-win-core-errorhandling-l1-1-0.dll
SekiWari\runtime\bin\api-ms-win-core-file-l1-1-0.dll
SekiWari\runtime\bin\api-ms-win-core-file-l1-2-0.dll
SekiWari\runtime\bin\api-ms-win-core-file-l2-1-0.dll
SekiWari\runtime\bin\api-ms-win-core-handle-l1-1-0.dll
SekiWari\runtime\bin\api-ms-win-core-heap-l1-1-0.dll
SekiWari\runtime\bin\api-ms-win-core-interlocked-l1-1-0.dll
SekiWari\runtime\bin\api-ms-win-core-libraryloader-l1-1-0.dll
SekiWari\runtime\bin\api-ms-win-core-localization-l1-2-0.dll
SekiWari\runtime\bin\api-ms-win-core-memory-l1-1-0.dll
SekiWari\runtime\bin\api-ms-win-core-namedpipe-l1-1-0.dll
SekiWari\runtime\bin\api-ms-win-core-processenvironment-l1-1-0.dll
SekiWari\runtime\bin\api-ms-win-core-processthreads-l1-1-0.dll
SekiWari\runtime\bin\api-ms-win-core-processthreads-l1-1-1.dll
SekiWari\runtime\bin\api-ms-win-core-profile-l1-1-0.dll
SekiWari\runtime\bin\api-ms-win-core-rtlsupport-l1-1-0.dll
SekiWari\runtime\bin\api-ms-win-core-string-l1-1-0.dll
SekiWari\runtime\bin\api-ms-win-core-synch-l1-1-0.dll
SekiWari\runtime\bin\api-ms-win-core-synch-l1-2-0.dll
SekiWari\runtime\bin\api-ms-win-core-sysinfo-l1-1-0.dll
SekiWari\runtime\bin\api-ms-win-core-timezone-l1-1-0.dll
SekiWari\runtime\bin\api-ms-win-core-util-l1-1-0.dll
SekiWari\runtime\bin\api-ms-win-crt-conio-l1-1-0.dll
SekiWari\runtime\bin\api-ms-win-crt-convert-l1-1-0.dll
SekiWari\runtime\bin\api-ms-win-crt-environment-l1-1-0.dll
SekiWari\runtime\bin\api-ms-win-crt-filesystem-l1-1-0.dll
SekiWari\runtime\bin\api-ms-win-crt-heap-l1-1-0.dll
SekiWari\runtime\bin\api-ms-win-crt-locale-l1-1-0.dll
SekiWari\runtime\bin\api-ms-win-crt-math-l1-1-0.dll
SekiWari\runtime\bin\api-ms-win-crt-multibyte-l1-1-0.dll
SekiWari\runtime\bin\api-ms-win-crt-private-l1-1-0.dll
SekiWari\runtime\bin\api-ms-win-crt-process-l1-1-0.dll
SekiWari\runtime\bin\api-ms-win-crt-runtime-l1-1-0.dll
SekiWari\runtime\bin\api-ms-win-crt-stdio-l1-1-0.dll
SekiWari\runtime\bin\api-ms-win-crt-string-l1-1-0.dll
SekiWari\runtime\bin\api-ms-win-crt-time-l1-1-0.dll
SekiWari\runtime\bin\api-ms-win-crt-utility-l1-1-0.dll
SekiWari\runtime\bin\awt.dll
SekiWari\runtime\bin\fontmanager.dll
SekiWari\runtime\bin\freetype.dll
SekiWari\runtime\bin\j2gss.dll
SekiWari\runtime\bin\java.dll
SekiWari\runtime\bin\java.exe
SekiWari\runtime\bin\javac.exe
SekiWari\runtime\bin\javadoc.exe
SekiWari\runtime\bin\javajpeg.dll
SekiWari\runtime\bin\javaw.exe
SekiWari\runtime\bin\jawt.dll
SekiWari\runtime\bin\jimage.dll
SekiWari\runtime\bin\jli.dll
SekiWari\runtime\bin\jrunscript.exe
SekiWari\runtime\bin\jsound.dll
SekiWari\runtime\bin\keytool.exe
SekiWari\runtime\bin\kinit.exe
SekiWari\runtime\bin\klist.exe
SekiWari\runtime\bin\ktab.exe
SekiWari\runtime\bin\lcms.dll
SekiWari\runtime\bin\mlib_image.dll
SekiWari\runtime\bin\msvcp140.dll
SekiWari\runtime\bin\net.dll
SekiWari\runtime\bin\nio.dll
SekiWari\runtime\bin\prefs.dll
SekiWari\runtime\bin\SekiWari
SekiWari\runtime\bin\SekiWari.bat
SekiWari\runtime\bin\serialver.exe
SekiWari\runtime\bin\server
SekiWari\runtime\bin\splashscreen.dll
SekiWari\runtime\bin\ucrtbase.dll
SekiWari\runtime\bin\vcruntime140.dll
SekiWari\runtime\bin\verify.dll
SekiWari\runtime\bin\w2k_lsa_auth.dll
SekiWari\runtime\bin\zip.dll
SekiWari\runtime\bin\server\jvm.dll
SekiWari\runtime\conf\logging.properties
SekiWari\runtime\conf\net.properties
SekiWari\runtime\conf\security
SekiWari\runtime\conf\sound.properties
SekiWari\runtime\conf\security\java.policy
SekiWari\runtime\conf\security\java.security
SekiWari\runtime\conf\security\policy
SekiWari\runtime\conf\security\policy\limited
SekiWari\runtime\conf\security\policy\README.txt
SekiWari\runtime\conf\security\policy\unlimited
SekiWari\runtime\conf\security\policy\limited\default_local.policy
SekiWari\runtime\conf\security\policy\limited\default_US_export.policy
SekiWari\runtime\conf\security\policy\limited\exempt_local.policy
SekiWari\runtime\conf\security\policy\unlimited\default_local.policy
SekiWari\runtime\conf\security\policy\unlimited\default_US_export.policy
SekiWari\runtime\legal\java.base
SekiWari\runtime\legal\java.compiler
SekiWari\runtime\legal\java.datatransfer
SekiWari\runtime\legal\java.desktop
SekiWari\runtime\legal\java.logging
SekiWari\runtime\legal\java.naming
SekiWari\runtime\legal\java.prefs
SekiWari\runtime\legal\java.scripting
SekiWari\runtime\legal\java.security.jgss
SekiWari\runtime\legal\java.security.sasl
SekiWari\runtime\legal\java.sql
SekiWari\runtime\legal\java.sql.rowset
SekiWari\runtime\legal\java.transaction.xa
SekiWari\runtime\legal\java.xml
SekiWari\runtime\legal\java.xml.crypto
SekiWari\runtime\legal\jdk.compiler
SekiWari\runtime\legal\jdk.javadoc
SekiWari\runtime\legal\jdk.unsupported
SekiWari\runtime\legal\java.base\aes.md
SekiWari\runtime\legal\java.base\asm.md
SekiWari\runtime\legal\java.base\c-libutl.md
SekiWari\runtime\legal\java.base\cldr.md
SekiWari\runtime\legal\java.base\COPYRIGHT
SekiWari\runtime\legal\java.base\icu.md
SekiWari\runtime\legal\java.base\LICENSE
SekiWari\runtime\legal\java.base\public_suffix.md
SekiWari\runtime\legal\java.base\unicode.md
SekiWari\runtime\legal\java.base\zlib.md
SekiWari\runtime\legal\java.compiler\COPYRIGHT
SekiWari\runtime\legal\java.compiler\LICENSE
SekiWari\runtime\legal\java.datatransfer\COPYRIGHT
SekiWari\runtime\legal\java.datatransfer\LICENSE
SekiWari\runtime\legal\java.desktop\colorimaging.md
SekiWari\runtime\legal\java.desktop\COPYRIGHT
SekiWari\runtime\legal\java.desktop\freetype.md
SekiWari\runtime\legal\java.desktop\giflib.md
SekiWari\runtime\legal\java.desktop\harfbuzz.md
SekiWari\runtime\legal\java.desktop\jpeg.md
SekiWari\runtime\legal\java.desktop\lcms.md
SekiWari\runtime\legal\java.desktop\libpng.md
SekiWari\runtime\legal\java.desktop\LICENSE
SekiWari\runtime\legal\java.desktop\mesa3d.md
SekiWari\runtime\legal\java.desktop\opengl.md
SekiWari\runtime\legal\java.logging\COPYRIGHT
SekiWari\runtime\legal\java.logging\LICENSE
SekiWari\runtime\legal\java.naming\COPYRIGHT
SekiWari\runtime\legal\java.naming\LICENSE
SekiWari\runtime\legal\java.prefs\COPYRIGHT
SekiWari\runtime\legal\java.prefs\LICENSE
SekiWari\runtime\legal\java.scripting\COPYRIGHT
SekiWari\runtime\legal\java.scripting\LICENSE
SekiWari\runtime\legal\java.security.jgss\COPYRIGHT
SekiWari\runtime\legal\java.security.jgss\LICENSE
SekiWari\runtime\legal\java.security.sasl\COPYRIGHT
SekiWari\runtime\legal\java.security.sasl\LICENSE
SekiWari\runtime\legal\java.sql\COPYRIGHT
SekiWari\runtime\legal\java.sql\LICENSE
SekiWari\runtime\legal\java.sql.rowset\COPYRIGHT
SekiWari\runtime\legal\java.sql.rowset\LICENSE
SekiWari\runtime\legal\java.transaction.xa\COPYRIGHT
SekiWari\runtime\legal\java.transaction.xa\LICENSE
SekiWari\runtime\legal\java.xml\bcel.md
SekiWari\runtime\legal\java.xml\COPYRIGHT
SekiWari\runtime\legal\java.xml\dom.md
SekiWari\runtime\legal\java.xml\jcup.md
SekiWari\runtime\legal\java.xml\LICENSE
SekiWari\runtime\legal\java.xml\xalan.md
SekiWari\runtime\legal\java.xml\xerces.md
SekiWari\runtime\legal\java.xml.crypto\COPYRIGHT
SekiWari\runtime\legal\java.xml.crypto\LICENSE
SekiWari\runtime\legal\java.xml.crypto\santuario.md
SekiWari\runtime\legal\jdk.compiler\COPYRIGHT
SekiWari\runtime\legal\jdk.compiler\LICENSE
SekiWari\runtime\legal\jdk.javadoc\COPYRIGHT
SekiWari\runtime\legal\jdk.javadoc\jquery-migrate.md
SekiWari\runtime\legal\jdk.javadoc\jquery.md
SekiWari\runtime\legal\jdk.javadoc\jqueryUI.md
SekiWari\runtime\legal\jdk.javadoc\jszip.md
SekiWari\runtime\legal\jdk.javadoc\LICENSE
SekiWari\runtime\legal\jdk.javadoc\pako.md
SekiWari\runtime\legal\jdk.unsupported\COPYRIGHT
SekiWari\runtime\legal\jdk.unsupported\LICENSE
SekiWari\runtime\lib\classlist
SekiWari\runtime\lib\ct.sym
SekiWari\runtime\lib\fontconfig.bfc
SekiWari\runtime\lib\fontconfig.properties.src
SekiWari\runtime\lib\jawt.lib
SekiWari\runtime\lib\jrt-fs.jar
SekiWari\runtime\lib\jvm.cfg
SekiWari\runtime\lib\jvm.lib
SekiWari\runtime\lib\modules
SekiWari\runtime\lib\psfont.properties.ja
SekiWari\runtime\lib\psfontj2d.properties
SekiWari\runtime\lib\security
SekiWari\runtime\lib\server
SekiWari\runtime\lib\tzdb.dat
SekiWari\runtime\lib\tzmappings
SekiWari\runtime\lib\security\blacklisted.certs
SekiWari\runtime\lib\security\cacerts
SekiWari\runtime\lib\security\default.policy
SekiWari\runtime\lib\security\public_suffix_list.dat
SekiWari\runtime\lib\server\Xusage.txt

**Comment by michaelknigge** [comment]
Hi,

sorry, I'm currently not familar with jpackage, so guess I can't be of any help....

Bye,
Michael
