### ISSUE TITLE
Error in java launcher.

### ISSUE THREAD

**Issue by nilkanth0018** [michaelknigge/janel#4]
I have two systems, both are running Windows 10, both having same java application installed and running well without Janel.

But when I try to run with Janel, one of the system run it without any issue and task manager shows custom process name instead of javaw.exe

But on another system I have done everything same, I have double check everything but not able to run the application with janel, it shows this error, **"Error in java launcher. error occurred while attempting to find Java class wes/wplayer/client/Start"**

Can you help me with this, please?

@michaelknigge

**Comment by michaelknigge** [comment]
This error ("error occurred while attempting to find Java class ...") is thrown if Janel is not able to find the main class. I can only assume that there is something different on your systems. It seems to me that the JAR file, that contains the class "wes/wplayer/client/Start" is missing...
