### ISSUE TITLE
Update Executables

### ISSUE THREAD

**Issue by BohnSeb** [michaelknigge/janel#5]
The enhancements you did to Janel4.2 are not available in the Executables found under the Executables folder of the repository.
I tested the "bitness" detection with the JanelConsole64.exe and a 32-bit JVM. It didn't threw the promised exception. Instead it just crashes without printing anything to the Console.

**Comment by BohnSeb** [comment]
P.S I tested it with the executables from the "enhanced" branch

**Comment by michaelknigge** [comment]
Sorry... seems to be a little bit confusing.... The "Executables" directory contains the old executables from the original release. maybe it's a good idea to delete this directory,

Official builds of the "enhanced" branch are available under https://github.com/michaelknigge/janel/releases
