### ISSUE TITLE
Double deletion on newer versions of windows with certain anti viruses

### ISSUE THREAD

**Issue by moose10141** [michaelknigge/janel#6]
Hi there,

We're using Janel for a couple of our Java applications and seem to be running into an issue 

The problem relates to the cleanup that occurs after calling `CreateJavaVM` from `void JVMLauncher::launch()` when `_UNICODE` is defined.

here is the two problematic snippets
```c++
		// from void JVMLauncher::launch()

		// setup options
		JavaVMInitArgs jvmInitArgs;
		setupJavaVMInitArgs(jvmInitArgs);

		result = CreateJavaVM(&pJvm,(void**)&pJniEnvironment,&jvmInitArgs);

		teardownJavaVMInitArgs(jvmInitArgs);
```

```c++
void JVMLauncher::teardownJavaVMInitArgs( JavaVMInitArgs& jvmInitArgs )
{
#ifdef _UNICODE
	jsize count = jvmInitArgs.nOptions;
	for (jsize index = 0; index < count; index++) {
		delete [] jvmInitArgs.options[index].optionString;
	}
#endif

}
```

The problem occurs when an active anti-virus has its own Java dll that it uses to monitor the application as in our case we have Sentinel One and it tries add itself as the agent by injecting the following arg.
```
-agentpath:C:\Program Files\SentinelOne\Sentinel Agent 22.3.4.612\SentinelJava64.dll
```

As a result the `jvmInitArgs` has its `jvmInitArgs.nOptions` increase by one which occurs after calling `CreateJavaVM` and so when it comes time to clean up the memory it tries to delete the last arg which has already been deallocated resulting in the following error.
```
FAILURE_BUCKET_ID:  HEAP_CORRUPTION_ACTIONABLE_BlockNotBusy_DOUBLE_FREE_80000003_ntdll.dll!RtlpFreeHeapInternal
```

There are a few possible solutions that I can think of such as recording the number of options before `CreateJavaVM` and resetting them after it as follows.
```c++
		// from void JVMLauncher::launch()

		// setup options
		JavaVMInitArgs jvmInitArgs;
		setupJavaVMInitArgs(jvmInitArgs);

		jsize allocatedNOptions = jvmInitArgs.nOptions;

		result = CreateJavaVM(&pJvm,(void**)&pJniEnvironment,&jvmInitArgs);

		jvmInitArgs.nOptions = allocatedNOptions;

		teardownJavaVMInitArgs(jvmInitArgs);
```
however this does result in a loss of information which could be used in the future although we could modify `teardownJavaVMInitArgs` to take in the number of args to clean up instead of relying on `nOptions`

Alternatively, we could record the memory addresses of the allocated strings and delete them to not be dependant on the `jvmInitArgs` as it can be unpredictable as to the state it will be left in after being passed to `CreateJavaVM`

Let me know what you think

Cheers

**Comment by jnbrunet** [comment]
We have exactly the same issue, also using Sentinel One. It has been a real headache for many people in the past 3 weeks and your report @moose10141 made us save a lot of debugging, thanks a lot for that.

Hopefully a fix such as those that you propose will be implemented to prevent lowering Sentinel One rules as it is not a viable solution for clients.

**Comment by michaelknigge** [comment]
This issue should be fixed with https://github.com/michaelknigge/janel/releases/tag/v4.2.0.127     

Sorry that it took that long to fix...
