### ISSUE TITLE
Fix crash if Java agent gets dynamically attached

### ISSUE THREAD

**Issue by michael-fl** [michaelknigge/janel#7]
Symptom:
On certain Windows (11) machines the Janel launcher does not start. It just
exists without any error message after a few milliseconds. Even specifying a
wrong Java main class in the .lap file does not make a difference. Hence, the
exit or crash happens prior calling the Java code.

Cause:
This happens only if certain anti virus programs are installed on the Windows
machine. One example is the SentinelOne anti virus. Such AV tools typically
attach themselves as agent via Java's Instrumentation API to be able to
intercept method calls.

The AV software modifies the array of initialization parameters of the JVM and
adds an additional one (-javaagent:...) behind the last one given (hence,
enlarges the array in memory). After the JVM was created, Janel code executes
teardownJavaVMInitArgs, which frees all allocated UTF parameter strings.
However, since the array is now larger and contains also the dynamically added
agent parameters, an attempt to free that memory will lead to a crash of the
application.

Siggested solution:
The method teardownJavaVMInitArgs is only called if the length of the JVM
parameter array has not changed after creation of the JVM. Otherwise the memory
is not released, which should be no problem, because those parameters do not
occupy much memory.

Note:
I already fixed this issue locally.

**Comment by michael-fl** [comment]
Hi @michaelknigge I would like to contribute here and push my fix into a branch and then open a pull request. However, looks like I'm not allowed to push to your repo (error 403). Is this on purpose?

**Comment by michaelknigge** [comment]
This issue should be fixed with https://github.com/michaelknigge/janel/releases/tag/v4.2.0.127 ... thank you for your fix and sorry that it took so long.... Spare time, you know...
